---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../components/app
namespace: "metube"
namePrefix: "metube-"
images:
  - name: "ghcr.io/alexta69/metube"
    newTag: "2025-07-01"
configMapGenerator:
  - name: app-config
    envs:
      - "app_config.env"
